### ISSUE TITLE
Feature Request - More services to disable/delete

### ISSUE THREAD

**Issue by Felipefpl** [shadesofdeath/ShadesTweaker#1]
If you click on "more" in this youtube's video you'll see A LOT of services that can be disabled/deleted to save CPU/RAM, a good addition to your nice tool:

https://www.youtube.com/watch?v=aIXDD4NKx60&t=159s

It would be nice to have an option to disable all services at once too. ;)

Thank you for this great tool and for your work with it btw.

**Comment by shadesofdeath** [comment]
Hello, thank you for your nice words. I will consider your suggestion and the program will become better with the directions and suggestions of you and others like you. I'll add more services as I get time, thanks.

**Comment by Felipefpl** [comment]
@shadesofdeath - hi, just small stuff, there is no need to fix it if you dont want it, the program crashes on win7, i wanted to look at it to see what changed, the app opens but it crashes right after it. Is it intentional?

**Comment by shadesofdeath** [comment]
> @shadesofdeath - hi, just small stuff, there is no need to fix it if you dont want it, the program crashes on win7, i wanted to look at it to see what changed, the app opens but it crashes right after it. Is it intentional?

This program requires Windows 10 and above to work properly
