### ISSUE TITLE
Debloat tabs should only shows installed or existing app within the system!

### ISSUE THREAD

**Issue by MassZERO** [shadesofdeath/ShadesTweaker#5]
Hi sir, 

Why is it on the debloat part you show all the apps??
Its very confusing, you should only show those apps that are installed within the MS Store and not show all that are not even existing or installed... 

Please change it to only show Apps that are existing within the windows system and not show all...
cause we dont know if it already exist or not... very confusing...

**Comment by shadesofdeath** [comment]
Merhaba varolmayanları zaten otomatik atlayacaktır.

**Comment by shadesofdeath** [comment]
Hello will automatically skip the non-existent ones anyway.
